### ISSUE TITLE
Unable to run the mc.MC()

### ISSUE THREAD

**Issue by varuncanamedi3301** [xopto/pyxopto#24]
Traceback (most recent call last):
  File "/content/pyxopto-master/examples/mcvox/voxelized_vessel.py", line 134, in <module>
    mc_obj = mc.Mc(
  File "/usr/local/lib/python3.10/dist-packages/pyxopto-0.2.3-py3.10.egg/xopto/mcvox/mc.py", line 350, in __init__
    super().__init__(types=types, options=options, cl_devices=cl_devices,
  File "/usr/local/lib/python3.10/dist-packages/pyxopto-0.2.3-py3.10.egg/xopto/mcbase/mcworker.py", line 1214, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/pyxopto-0.2.3-py3.10.egg/xopto/mcbase/mcworker.py", line 198, in __init__
    self._cl_queue = cl.CommandQueue(
TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, context: pyopencl._cl.Context, device: Optional[pyopencl._cl.Device] = None, properties: object = 0) -> None

Invoked with types: pyopencl._cl.CommandQueue, pyopencl._cl.Context, kwargs = { properties: NoneType }

I get this error everytime I run the example codes. Please help !

**Comment by xopto** [comment]
The error report is strange since the arguments match the required types. Is it possible that there are two pyopencl libraries in the system path and the used pyopencl module is loading the wrong shared library?
(1) Try to import the clinfo utility "from xopto.cl import clinfo" and run "clinfo()". This will output all the available OpenCL devices and their capabilities.
(2) Try to run the example code from pyopencl documentation (https://documen.tician.de/pyopencl/) and see if it works.

**Comment by fire9291** [comment]
> The error report is strange since the arguments match the required types. Is it possible that there are two pyopencl libraries in the system path and the used pyopencl module is loading the wrong shared library? (1) Try to import the clinfo utility "from xopto.cl import clinfo" and run "clinfo()". This will output all the available OpenCL devices and their capabilities. (2) Try to run the example code from pyopencl documentation (https://documen.tician.de/pyopencl/) and see if it works.

I got the same Err. Example codes can not be run correctly. When run clinfo.info() it returns:
Platform name: NVIDIA CUDA
Platform profile: FULL_PROFILE
Platform vendor: NVIDIA Corporation
Platform version: OpenCL 1.2 CUDA 10.1.104
---------------------------------------------------------------
	Device name: GeForce GT 730
	Device type: ALL | GPU
	Device available: Yes
	Device maximum clock frequency: 901 MHz
	Device default address space: 64 bit
        ......

**Comment by fire9291** [comment]
I got the same. Have you ever fixed it?

**Comment by varuncanamedi3301** [comment]
Yes, I did fix it somehow. In line 198 of the mcbase.py file

 self._cl_queue = cl.CommandQueue(
                self._cl_context, properties=cl_cq_properties)

change cl_cq_properties=0. I don't know why it works but it works.

**Comment by xopto** [comment]
It seems that on some platforms the properties argument of the CommandQueue does not take a None value (even though it is documented to allow None or 0 => https://documen.tician.de/pyopencl/runtime_queue.html#pyopencl.CommandQueue).

For those who observe the error, a temporary fix is to force 0 instead of None by modifying xopto/mcbase/mcworker.py file:
"cl_cq_properties = None" => "cl_cq_properties = 0"
This change should have no side effects.

**Comment by fire9291** [comment]
It realy works!  Thanks a lot.

Another question is how can I adjust the ligtht source. I want a focused Guassian Beam with focus in tissue, rather than a collimated one.  I believe this can be achieved. Many thanks!

**Comment by xopto** [comment]
A true Gaussian beam can be modeled only if the wave nature of light is considered (which the MC method does not). However, there are approximations that one can use. A couple of suggestions:

1. Use a collimated Gaussian beam and transform the initial propagation direction by an ideal thin lens. This will give a perfect focus spot at the focal point of the lens. Depending on the refractive indices of the tissue and surrounding medium, a refraction and packet weight reduction should be calculated at the tissue boundary.

2. Model the focusing of a Gaussian beam with a cropped cone (consider the radius of the two round surfaces as sigma, the smaller one is located in the focus/tissue and the larger one on the tissue surface or above the surface). To launch a packet, randomly sample one point from the large round surface and one point from the smaller round surface. Connect the two points to obtain the initial propagation direction of the packet and compute the intersection with the tissue surface if launching from above the surface. The random sampling at the two surfaces is essentially the same as for the collimated Gaussian beam but with different sigmas. Depending on the refractive indices of the tissue and surrounding medium, a refraction and packet weight reduction should be calculated at the tissue boundary.

Note that both suggestions require a new source with custom OpenCL code. In both cases, a good starting point would be the already implemented collimated Gaussian beam source.

**Comment by Randall531** [comment]
Hello, I still experience the same type-error even after i changed cl_cq_properties = None to cl_cq_properties = 0 when i was trying to run the basic.py file. Anyone still experiences it?

**Comment by xopto** [comment]
On some platforms it now seems that neither None nor 0 works.

In this case, try to modify xopto/mcbase/mcworker.py by using an empty list instead of None or 0 (a sequence of keys and values should be allowed for OpenCL version >= 2.0): 
"cl_cq_properties = None" => "cl_cq_properties = []"

**Comment by Randall531** [comment]
I have tried to change and it doesnt seem to work. I have also tried changing the other = None  to = [] however, still receive the same error.

TypeError: __init__(): incompatible function arguments. The following argument types are supported:
    1. __init__(self, context: pyopencl._cl.Context, device: typing.Optional[pyopencl._cl.Device] = None, properties: object = 0) -> None

Invoked with types: pyopencl._cl.CommandQueue, pyopencl._cl.Context, kwargs = { properties: NoneType }

Not sure whats the reason

**Comment by xopto** [comment]
The error report implies that the cl_cq_properties argument (properties) is still set to None (not to 0 or []):
    Invoked with types: pyopencl._cl.CommandQueue, pyopencl._cl.Context, kwargs = { properties: NoneType }.

Is it possible that there are two pyxopto packages in the python path and you are editing the mcworker.py of the one that is not being used?

What is the full error report? Is the error originating from line 195 or line 199 of the mcworker.py module?
If the error originates from line 195 (not the usual line 199) try to force properties argument to 0 or []:
   "self._cl_context = cl.Context(self._cl_devices)" => "self._cl_context = cl.Context(self._cl_devices, properties=0)"

**Comment by Randall531** [comment]
Yes you are right, I found another pyxopto package being used in my venv folder. I edited =None to =[] and it has worked! Thank you

**Comment by lpattelli** [comment]
Hi all,
just writing to say that I also encountered the same problem in a recent pyxopto installation.
Changing `cl_cq_properties = None` to `cl_cq_properties = 0` in [this line](https://github.com/xopto/pyxopto/blob/be45fd6d44696b5a40a327dd0f494d46f5585fda/xopto/mcbase/mcworker.py#L184) of mcbase/mcworker.py fixed the issue also for me, as previously suggested in this thread.

Perhaps the code can be updated initializing `cl_cq_properties` with either `0` or `[]`, and the issue can be closed?
